language: node_js
node_js:
   - 8
cache:
  directories:
    - node_modules

branches:
   only:
      - master
      - development

notifications:
  email:
    on_success: change
    on_failure: always

before_script:
   - npm install -g @angular/cli
script:
   - ng build --prod

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$TOKEN"
  message: "Deployed to Firebase!"
